name: Build binaries
on: [push]

jobs:
  linux64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      BITFOCUS_S3: ${{secrets.BITFOCUS_S3}}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm libudev-dev libusb-1.0-0-dev
      - name: yarn and dist
        run: |
          yarn
          yarn run dist

          # manually tar it, to preserve the symlinks
          cd electron-output
          VERSION=$(node -e "console.log(require('../package.json').version)")
          mv linux-unpacked companion-$VERSION
          tar -cvzf companion-$VERSION.tar.gz companion-$VERSION
      - name: rename and upload stuff
        if: ${{ env.BITFOCUS_S3 }}
        run: node ./tools/build_rename_git.js
        env:
          CI_BUILD_OS: linux
          BITFOCUS_S3: ${{ secrets.BITFOCUS_S3 }}
          BITFOCUS_KEY: ${{ secrets.BITFOCUS_ACCESS }}
          BITFOCUS_SECRET: ${{ secrets.BITFOCUS_SECRET }}

  osx:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      BITFOCUS_S3: ${{secrets.BITFOCUS_S3}}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn and dist
        run: |
          yarn
          yarn run dist
      - name: rename and upload stuff
        if: ${{ env.BITFOCUS_S3 }}
        run: node ./tools/build_rename_git.js
        env:
          CI_BUILD_OS: osx
          CI_BUILD_ARCH: x64
          BITFOCUS_S3: ${{ secrets.BITFOCUS_S3 }}
          BITFOCUS_KEY: ${{ secrets.BITFOCUS_ACCESS }}
          BITFOCUS_SECRET: ${{ secrets.BITFOCUS_SECRET }}

  # osx-arm64:
  #   runs-on: macos-11
  #   strategy:
  #     matrix:
  #       node-version: [12.x]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: yarn and dist
  #       run: |
  #         yarn
  #         yarn run dist
  #     - name: rename and upload stuff
  #       run: node ./tools/build_rename_git.js
  #       env:
  #         CI_BUILD_OS: osx
  #         CI_BUILD_ARCH: arm64
  #         BITFOCUS_S3: ${{ secrets.BITFOCUS_S3 }}
  #         BITFOCUS_KEY: ${{ secrets.BITFOCUS_ACCESS }}
  #         BITFOCUS_SECRET: ${{ secrets.BITFOCUS_SECRET }}

  win64:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      BITFOCUS_S3: ${{secrets.BITFOCUS_S3}}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn and dist
        run: |
          # This fixes it somehow, and without it we get no logs from any shell scripts which are run
          yarn config set script-shell bash

          yarn
          yarn run dist
      - name: rename and upload stuff
        if: ${{ env.BITFOCUS_S3 }}
        run: node ./tools/build_rename_git.js
        env:
          CI_BUILD_OS: win64
          BITFOCUS_S3: ${{ secrets.BITFOCUS_S3 }}
          BITFOCUS_KEY: ${{ secrets.BITFOCUS_ACCESS }}
          BITFOCUS_SECRET: ${{ secrets.BITFOCUS_SECRET }}
